# Generated by Django 5.2.7 on 2026-10-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modalidades',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='modalidades.modalidadeesportiva'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
