# Generated by Django 5.2.7 on 2026-10-01 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadeEsportiva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'modalidades_esportivas',
            },
        ),
        migrations.CreateModel(
            name='TimeXModalidade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('masculino_ou_feminino', models.CharField(max_length=10)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to=settings.AUTH_USER_MODEL)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='modalidades.modalidadeesportiva')),
            ],
            options={
                'db_table': 'timexjogador',
                'constraints': [models.UniqueConstraint(fields=('jogador', 'modalidade', 'masculino_ou_feminino'), name='jogador_modalidade_sexo_unico')],
            },
        ),
    ]
