# Generated by Django 5.2.7 on 2026-10-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechado', models.BooleanField(default=False)),
                ('limite_participantes', models.IntegerField(blank=True, null=True)),
                ('local', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('duracao', models.IntegerField()),
                ('custo', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_criados', to=settings.AUTH_USER_MODEL)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='modalidades.modalidadeesportiva')),
            ],
            options={
                'db_table': 'treinos',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoTreino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_treino', to=settings.AUTH_USER_MODEL)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='treinos.treino')),
            ],
            options={
                'db_table': 'inscricao_treino',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'treino'), name='usuario_treino_unico')],
            },
        ),
    ]
