create table public.modalidades_esportivas (
    id integer generated by default as identity primary key,
    nome varchar(100) not null,
    descricao text,
    created_at timestamp not null default current_timestamp,
    constraint modalidades_esportivas_nome_unique unique (nome)
);

create index modalidades_esportivas_nome_idx on public.modalidades_esportivas (nome);

create table public.usuarios (
    id integer generated by default as identity primary key,
    nome varchar(100) not null,
    sobrenome varchar(100) not null,
    email varchar(100) not null,
    usuario varchar(100) not null,
    senha_hash varchar(255) not null,
    modalidade_preferida integer not null references public.modalidades_esportivas (id),
    foto_perfil varchar(500),
    created_at timestamp not null default current_timestamp,
    constraint usuarios_usuario_unique unique (usuario),
    constraint usuarios_email_unique unique (email)
);

create index usuarios_modalidade_preferida_idx on public.usuarios (modalidade_preferida);

create table public.avisos (
    id integer generated by default as identity primary key,
    criador integer not null references public.usuarios (id),
    titulo varchar(100) not null,
    descricao varchar(100) not null
);

create index avisos_criador_idx on public.avisos (criador);

create table public.treinos (
    id integer generated by default as identity primary key,
    criador integer not null references public.usuarios (id),
    modalidade_id integer not null references public.modalidades_esportivas (id),
    limite_participantes integer,
    local varchar(100) not null,
    data_hora timestamp not null,
    duracao integer not null,
    custo integer,
    observacoes text,
    created_at timestamp not null default current_timestamp
);

create index treinos_criador_idx on public.treinos (criador);

create index treinos_modalidade_id_idx on public.treinos (modalidade_id);

create table public.inscricao_treino (
    usuario integer references public.usuarios (id),
    treino integer references public.treinos (id),
    presenca boolean not null
);

create index inscricao_treino_usuario_idx on public.inscricao_treino (usuario);

create index inscricao_treino_treino_idx on public.inscricao_treino (treino);
